Integer dimensions are sometimes returned as the string `(other)`
singer-io/tap-ga4 pull request #37
Opened 2022-12-12 18:53 UTC by leslievandemark

# Description of change
Integer dimensions are sometimes returned as the string `(other)`. This pr updates their schema to accept strings as well. 
reference: https://support.google.com/analytics/answer/9309767
# Manual QA steps
 - Ran failing test with this field selection `main - INFO Selected fields for stream 47ae1330-f7df-480f-8dfa-ca08698f1782: total_users, screen_page_views, hour, property_id, _sdc_record_hash, nth_minute, screen_page_views_per_session, active1_day_users, wau_per_mau, stream_name, average_purchase_revenue, minute, date, active7_day_users, transactions, event_count, account_id, events_per_session` 
 - updated schema in discovery and test passed. 
 
# Risks
 - It's not documented which dimensions can be returned as `(other)` we originally just thought it was date times. We've now seen in for `hour`, `minute`, and `nth_minute`. I am setting it for all integer dimensions, because it seems there is no reason they couldn't get an `(other)`. 
 
# Rollback steps
 - revert this branch

2024-02-27 11:05 UTC, cosimon requested changes

2024-02-27 11:05 UTC, cosimon commented on tap_ga4/discover.py
> +                ]}
```suggestion
            schema["properties"][dimension] =  {"type": ["integer", "string", "null"]},
```

2024-02-27 11:25 UTC, sgandhi1311 commented on tap_ga4/discover.py
> +                ]}
done

2024-02-28 10:57 UTC, cosimon approved these changes

2024-02-28 13:12 UTC, merged